### ISSUE TITLE
Use of `F` in `sd_compute_dist_stats()`

### ISSUE THREAD

**Issue by Aeilert** [PIP-Technical-Team/wbpip#168]
Hi @tonyfujs 

While looking a bit closer at the `wbpip` package I came a cross this code. The use if `F` here is unsafe since `F` and `T` are substitutes for `TRUE` and `FALSE`

https://github.com/PIP-Technical-Team/wbpip/blob/e23b2165bcd8814b78a589c99d39e72ea4307acb/R/sd_compute_dist_stats.R#L70

https://github.com/PIP-Technical-Team/wbpip/blob/e23b2165bcd8814b78a589c99d39e72ea4307acb/R/sd_compute_dist_stats.R#L85-L97

**Comment by tonyfujs** [comment]
Good catch @Aeilert . @randrescastaneda I believe you implemented this one. What does F stands for here? Can we replace it by something more explicit? Thanks!

**Comment by randrescastaneda** [comment]
Hey guy (@tonyfujs and @Aeilert ), 

You're right. I should not have used `F` for the object name... I totally forgot about the `TRUE` and `FALSE` abbreviations. Anyhow, `F` stands for the observations' weights for each simulated observation. Since the simulation is done along the distribution, the value of `F` is just the cumulative weight  from (almost) zero to one. You could replace it for `weight_range` or something like that. I wanted to replace it but I am not sure from which branch I should use to check out my own branch. You could either tell me the name of the branch or do the fix yourself. Just let me know. 

Best,

**Comment by Aeilert** [comment]
Thanks @randrescastaneda, 

I can make the change.
